version: '3'
services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.2
    restart: "no"
    ports:
      - ${FORWARDED_PORT}:8080
    env_file:
        - .env
        - .env.dev
    volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    networks:
      - postgis_postgis

networks:
   postgis_postgis:
      driver: bridge
      external: true
