#This service depends on the postgis_postgis docker network
#Start the posrgis container first

#1. Create the folders data and servers. 
#   the script ./sudo_create_folders.sh will do the following
#   steps for you
#2. Create the file servers/servers.json, empty
#3. Change the owner for the folder data
#     sudo chown -R 5050:5050 data
#4. Start the server:
#   docker-compose up
#5. Visit the page http://localost:5050

services:
   pgadmin4:
      image: dpage/pgadmin4:8.3
      env_file:
#por un bug de docker-compose, no lee correctamente .env.dev
#para la sustitución de variables en el propio docker compose
#sinembargo .env sí lo lee.
#Como se puede tener varios ficheros de configuración, uso los dos

        - .env
        - .env.prod
      volumes:
        - ./pgadmin4_prod/data:/var/lib/pgadmin
        - ./pgadmin4_prod/servers/servers.json:/pgadmin4/servers.json
      ports:
        #VERY VERY IMPORTANT: if you forget 127.0.0.1, Docker
        #will introduce rules in iptables to open the exposed port
        #to the world --> DANGER. 
        - 127.0.0.1:${PRODUCTION_FORWARDED_PORT}:80
      restart: unless-stopped
      networks:
        - postgis_postgis
networks:
  postgis_postgis:
      external: true

